name: Firestore → Notion Sync

on:
  workflow_dispatch:        # allow manual run
  schedule:
    - cron: "0 9 * * *"     # run every day at 9 AM UTC (2:30 PM IST)

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install minimal deps
        run: |
          npm init -y
          npm install --no-save firebase-admin @notionhq/client

      - name: Run Firestore → Notion sync
        env:
          FIREBASE_SA_JSON: ${{ secrets.FIREBASE_SA_JSON }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          FIREBASE_UID: ${{ secrets.FIREBASE_UID }}
          NOTION_TITLE_PROP: "Content"
        run: node scripts/sync-firestore-to-notion.mjs
